// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// var_lhood
double var_lhood(arma::mat Y, arma::vec par, int lags, int print_level);
RcppExport SEXP VARext_var_lhood(SEXP YSEXP, SEXP parSEXP, SEXP lagsSEXP, SEXP print_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< int >::type print_level(print_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(var_lhood(Y, par, lags, print_level));
    return rcpp_result_gen;
END_RCPP
}
// var_lhood_grad_numeric
arma::vec var_lhood_grad_numeric(arma::mat Y, arma::vec par, int lags, int print_level);
RcppExport SEXP VARext_var_lhood_grad_numeric(SEXP YSEXP, SEXP parSEXP, SEXP lagsSEXP, SEXP print_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type par(parSEXP);
    Rcpp::traits::input_parameter< int >::type lags(lagsSEXP);
    Rcpp::traits::input_parameter< int >::type print_level(print_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(var_lhood_grad_numeric(Y, par, lags, print_level));
    return rcpp_result_gen;
END_RCPP
}
// var_sim_e
arma::mat var_sim_e(arma::vec a, arma::mat A, arma::mat y0, arma::mat e);
RcppExport SEXP VARext_var_sim_e(SEXP aSEXP, SEXP ASEXP, SEXP y0SEXP, SEXP eSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type e(eSEXP);
    rcpp_result_gen = Rcpp::wrap(var_sim_e(a, A, y0, e));
    return rcpp_result_gen;
END_RCPP
}
// var_e
arma::mat var_e(arma::mat Sigma, int n_pds);
RcppExport SEXP VARext_var_e(SEXP SigmaSEXP, SEXP n_pdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n_pds(n_pdsSEXP);
    rcpp_result_gen = Rcpp::wrap(var_e(Sigma, n_pds));
    return rcpp_result_gen;
END_RCPP
}
// var_sim
arma::mat var_sim(arma::vec a, arma::mat A, arma::mat y0, arma::mat Sigma, int n_pds);
RcppExport SEXP VARext_var_sim(SEXP aSEXP, SEXP ASEXP, SEXP y0SEXP, SEXP SigmaSEXP, SEXP n_pdsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type y0(y0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< int >::type n_pds(n_pdsSEXP);
    rcpp_result_gen = Rcpp::wrap(var_sim(a, A, y0, Sigma, n_pds));
    return rcpp_result_gen;
END_RCPP
}
