# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

var_lhood <- function(Y, par, lags = 1L, print_level = 0L) {
    .Call('VARext_var_lhood', PACKAGE = 'VARext', Y, par, lags, print_level)
}

var_lhood_grad_numeric <- function(Y, par, lags = 1L, print_level = 0L) {
    .Call('VARext_var_lhood_grad_numeric', PACKAGE = 'VARext', Y, par, lags, print_level)
}

var_sim_e <- function(a, A, y0, e) {
    .Call('VARext_var_sim_e', PACKAGE = 'VARext', a, A, y0, e)
}

var_e <- function(Sigma, n_pds) {
    .Call('VARext_var_e', PACKAGE = 'VARext', Sigma, n_pds)
}

var_sim <- function(a, A, y0, Sigma, n_pds) {
    .Call('VARext_var_sim', PACKAGE = 'VARext', a, A, y0, Sigma, n_pds)
}

