# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rou_y <- function(N, sd_u) {
    .Call('VARext_rou_y', PACKAGE = 'VARext', N, sd_u)
}

M_i_ig <- function(Y, i, a, A, Sigma, print_level = 0L) {
    .Call('VARext_M_i_ig', PACKAGE = 'VARext', Y, i, a, A, Sigma, print_level)
}

var_cm <- function(Y, a, A) {
    .Call('VARext_var_cm', PACKAGE = 'VARext', Y, a, A)
}

disc_cv <- function(Y, M) {
    .Call('VARext_disc_cv', PACKAGE = 'VARext', Y, M)
}

disc_skew <- function(Y, M) {
    .Call('VARext_disc_skew', PACKAGE = 'VARext', Y, M)
}

disc_obj <- function(m_i, Y, i, a, A, Sigma, w, print_level = 0L) {
    .Call('VARext_disc_obj', PACKAGE = 'VARext', m_i, Y, i, a, A, Sigma, w, print_level)
}

disc_grad <- function(m_i, Y, i, a, A, Sigma, w) {
    .Call('VARext_disc_grad', PACKAGE = 'VARext', m_i, Y, i, a, A, Sigma, w)
}

var_lhood_N <- function(Y, par, lags = 1L, print_level = 0L, cond = TRUE) {
    .Call('VARext_var_lhood_N', PACKAGE = 'VARext', Y, par, lags, print_level, cond)
}

var_lhood <- function(Y, par, lags = 1L, print_level = 0L, cond = TRUE) {
    .Call('VARext_var_lhood', PACKAGE = 'VARext', Y, par, lags, print_level, cond)
}

var_lr_mu <- function(a, A, lags) {
    .Call('VARext_var_lr_mu', PACKAGE = 'VARext', a, A, lags)
}

var_lr_mu_grad <- function(a, A, lags) {
    .Call('VARext_var_lr_mu_grad', PACKAGE = 'VARext', a, A, lags)
}

var_lr_variance <- function(A, Sigma, lags = 1L, contemp = TRUE) {
    .Call('VARext_var_lr_variance', PACKAGE = 'VARext', A, Sigma, lags, contemp)
}

var_init_lhood_grad_numeric <- function(Y0, par, n_var, lags = 1L) {
    .Call('VARext_var_init_lhood_grad_numeric', PACKAGE = 'VARext', Y0, par, n_var, lags)
}

var_lhood_grad <- function(Y, par, lags = 1L, print_level = 0L, cond = TRUE) {
    .Call('VARext_var_lhood_grad', PACKAGE = 'VARext', Y, par, lags, print_level, cond)
}

var_lhood_grad_vcv <- function(Y, par, lags = 1L, print_level = 0L, cond = TRUE) {
    .Call('VARext_var_lhood_grad_vcv', PACKAGE = 'VARext', Y, par, lags, print_level, cond)
}

var_lhood_grad_numeric <- function(Y, par, lags = 1L, print_level = 0L, cond = TRUE) {
    .Call('VARext_var_lhood_grad_numeric', PACKAGE = 'VARext', Y, par, lags, print_level, cond)
}

var_lhood_hessian_numeric <- function(Y, par, lags = 1L, print_level = 0L, cond = TRUE) {
    .Call('VARext_var_lhood_hessian_numeric', PACKAGE = 'VARext', Y, par, lags, print_level, cond)
}

var_sim_e <- function(a, A, y0, e) {
    .Call('VARext_var_sim_e', PACKAGE = 'VARext', a, A, y0, e)
}

var_e <- function(Sigma, n_pds) {
    .Call('VARext_var_e', PACKAGE = 'VARext', Sigma, n_pds)
}

var_sim <- function(a, A, y0, Sigma, n_pds) {
    .Call('VARext_var_sim', PACKAGE = 'VARext', a, A, y0, Sigma, n_pds)
}

markov_sim <- function(n, M, s0, n_s) {
    .Call('VARext_markov_sim', PACKAGE = 'VARext', n, M, s0, n_s)
}

